### ISSUE TITLE
Top intro pararaph proposed changes

### ISSUE THREAD

**Issue by Saallen** [MozillaFestival/test-mozfest-program-2018#3]
Change: Before you submit, please make use of the following tools

TO:  Before you submit:

- Ensure you know which [Space ](https://mozillafestival-org-sta-pr-894.herokuapp.com/spaces)you will submit your proposal under

- You have read [What makes a great MozFest session](https://medium.com/mozilla-festival/what-makes-a-great-mozilla-festival-session-529dff105185)

- Checked if our [FAQ] ( link later) can help with any outstanding questions you might have

**Comment by mmmavis** [comment]
@Saallen do we have the FAQ link? If not I'll just include the top 2 links for now.

**Comment by Saallen** [comment]
Link is coming from @amirad

**Comment by Saallen** [comment]
@mmmavis can you also please amend

Change: Before you submit, please make use of the following tools

TO- Before you submit:

**Comment by mmmavis** [comment]
> can you also please amend
> Change: Before you submit, please make use of the following tools
> TO- Before you submit:

fixed

**Comment by amirad** [comment]
Adding the link to FAQ here: https://docs.google.com/document/d/16I55way_DQeFXII1CLtY--p8BXcIMb9bhPQAavWZmLY/edit?usp=sharing

Still working on blogpost/doc for 7 steps to a great mozfest proposal

**Comment by mmmavis** [comment]
FAQ link added! http://mozillafestival-org-staging.herokuapp.com/proposals
