### ISSUE TITLE
QA Change info in top paragraph 

### ISSUE THREAD

**Issue by Saallen** [MozillaFestival/test-mozfest-program-2018#4]
Change: Should you would like to submit your session in another language we have outlined ways for you to do so within this form. If you have difficulty submitting via a texted based form please reach out to us on the email below to discuss other accessibility options.

TO: Should you like to submit your session in another language we have outlined ways for you to do so within this form. If you have difficulty submitting via a texted based form please reach out to us on the email below to discuss other accessibility options.

cc @mmmavis

**Comment by mmmavis** [comment]
Fixed!
