### ISSUE TITLE
QA - LANGUAGE SELECTION

### ISSUE THREAD

**Issue by Saallen** [MozillaFestival/test-mozfest-program-2018#7]
We state :If you wish to lead your session in another language or support your session in multiple languages, please let us know. From previous Mozfests, we know we have a substancial number of Spanish, German and French speakers in attendance.

However in the language selection we only offer one option for choosing a language- 
we should make this piece multiple selection cc @mmmavis

**Comment by mmmavis** [comment]
Ah didn't know that question was supposed to be a multiple choices question. I'll update the form on MozFest site. @Saallen do you mind updating your Google Form for future references?

**Comment by Saallen** [comment]
We didnt make it multiple but when you read the question "support your session in multiple languages" we dont allow for that selection of which multiple languages-
Yes will update

**Comment by mmmavis** [comment]
Should be fixed now: https://mozillafestival-org-sta-pr-894.herokuapp.com/
